name: Asana Task Update

on:
  pull_request:
    types: [ opened ]

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: yossy/asana-go
    - name: build package
      run: make build
    - name: Update asana task
      run: bin/updatetask -pat pat -pr pr -notes notes
