name: Asana Task Update

on:
  pull_request:
    types: [ opened ]

jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update asana task
      uses: yossy/asana-go
      run: go run github.com/yossy/asana-go/cmd/asana
